### ISSUE TITLE
Add ServiceClaim's runtime validation

### ISSUE THREAD

**Issue by filariow** [primaza/primaza#263]
# Story

As a Primaza Developer,
I would like to have ServiceClaim validated at runtime
so that I can remove ValidatingWebhooks

## Background

Actual ServiceClaim life-cycle is as depicted in the following diagrams:

```mermaid
flowchart TD
    subgraph state
        sStart((Claim\ncreated))
        sPending[Pending]
        sResolved[Resolved]

        sStart --> sPending
        sPending <--> sResolved
    end
    subgraph flow
        Start((Claim\ncreated)) --> Pending
        Pending  -->|Service matched| Resolved
        Resolved -->|Service unmatched| Pending
    end
```

ServiceClaim validation happens through ValidatingWebhooks.
We'd like to remove ValidatingWebhooks because of their complexity and the impossibility of having them namespaced-scoped.

## Out of scope

NA

## In Scope

* Remove ServiceClaim's ValidatingWebhooks
* Implement runtime validation for ServiceClaims

## Approach

To effectively remove the ValidatingWebhooks we need to implement runtime validation for ServiceClaims.

The checks we need to perform are:
* Prevent mutually exclusive fields to be defined at the same time
* Guarantee immutability for immutable fields
* Prevent some fields to be present in the wrong context

### Mutually exclusive fields

Mutually exclusive fields can be validated using kubernetes CRD Validations.
It is just needed to move them as child of a parent with `MinProperties` and `MaxProperties` set to 1.

As an example ServiceClaim's `environmentTag` and `applicationClusterContext` can not be defined at the same time.
They can be moved as child of a `target` property, and we can set the following constraints on `target` Go struct:

```golang
// +kubebuilder:validation:MaxProperties:=1
// +kubebuilder:validation:MinProperties:=1
```

### Guarantee Immutability

Immutability is implemented in the following way.

When a ServiceClaim is created, if the validation fails it's state is set to `Invalid`.
Subsequent updates on the ServiceClaim may restore its validity, then it would be moved to `Pending`.

When a valid ServiceClaim is moved to `Pending` its immutable fields are copied over to `status`.
Immutable fields in `status` are NEVER updated.
Now on the controller always relies on values in `status`.

In `Pending` state, new changes of its specification may mutate immutable fields.
When it happens, a new Error conditions is added to the ones at `status.conditions` and immutable fields in `status` are not updated.

### Wrong context

When creating a ServiceClaim in an Application Namespace nor `environmentTag` neither `applicationClusterContext` can be defined.
To prevent this, the same validation mechanism described in [Guarantee Immutability](#guarantee-immutability) can be implemented.

This check can be completely removed by introducing a new CRD without the prohibited fields.

### New life cycle

Putting all together, the following workflow should be implemented.

```mermaid
%%{init: {'theme':'dark'}}%%
flowchart TD
    subgraph Legend
        direction LR
        A:::invisible
        B:::invisible
        C:::invisible
        D:::invisible

        A -->|Already Implemented| B
        C -->|To be implemented| D
    end
    subgraph States
        sStart((Claim\ncreated))
        sInvalid[Invalid]
        sPending[Pending]
        sResolved[Resolved]

        sInvalid --> sPending
        sStart --> sPending
        sStart --> sInvalid
        sPending <--> sResolved
    end
    subgraph Flow
        Invisible:::invisible
        Start ~~~ Invisible

        IsChangeLegalPending{Is change\nlegal?}
        IsChangeLegalResolved{Is change\nlegal?}
        ToggleValidation([Set Validation\nerror in Conditions])
        SatisfiedValidation([Add satisfied\nValidation Condition])

        Start((Claim\ncreated)) -->  IsValid
        IsValid  -->|Yes| SatisfiedValidation
        SatisfiedValidation --> Pending
        IsValid  -->|No| Invalid
        Invalid  -->|Claim is Updated| IsValid
        Pending  -->|Claim is Updated| IsChangeLegalPending
        IsChangeLegalPending -->|Yes| Pending

        subgraph validation
          IsValid{Is Valid?}
          Invalid
        end

        subgraph resolution[resolution]
          Pending  -->|Service matched| Resolved
          Resolved -->|Service unmatched| Pending
        end

        Resolved -->|Claim is Updated| IsChangeLegalResolved
        IsChangeLegalResolved -->|Yes| Resolved

        subgraph update
          IsChangeLegalPending -->|No| ToggleValidation
          IsChangeLegalResolved -->|No| ToggleValidation
        end

        %% formatting %%
        update:::invisible
        resolution:::invisible
        validation:::invisible
    end

    Invisible ~~~ States
    States ~~~ Legend
    classDef invisible display:none;

    style sPending fill:green,color:black;
    style sResolved fill:green,color:black;

    linkStyle 0,3,5,14,15 stroke:green,stroke-width:5px;

    style Pending fill:green,color:black;
    style Resolved fill:green,color:black;
```

## Acceptance Criteria

* Development
:grey_question: ServiceClaim ControlPlane's Controller checks for Service Claim validity
:grey_question: ServiceClaim Application Agent's Controller checks for ServiceClaim validity
:grey_question: ServiceClaim webhooks are removed
:grey_question: ServiceClaim CRDs are refactored wrt mutually exclusive field remediation

 * QE
:grey_question: There are test cases for runtime validation of ServiceClaim in Control Plane on creation and update
:grey_question: There are test cases for runtime validation of ServiceClaim in Application Namespaces on creation and update

 * Docs
:grey_question: Update ServiceClaim doc
:grey_question: Update architecture document with any changes while implementing

### Legend

- 🔲  To do
- ☑️  Done
- 🔲  ~Unsatisfied~

**Comment by baijum** [comment]
@filariow If the immutable resources fields are manually changed using `kubectl edit`, is that need to be prevented?

**Comment by baijum** [comment]
@filariow 

The last sentence of the "Wrong context" section reads like this:

> This check can be completely removed by introducing a new CRD without the prohibited fields.

This is just a remark and not a proposal in this story, right?

**Comment by filariow** [comment]
> @filariow If the immutable resources fields are manually changed using `kubectl edit`, is that need to be prevented?

We actually can not do that without Validating Webhooks, so it can not be prevented if we remove them.

> The last sentence of the "Wrong context" section reads like this:
> 
> > This check can be completely removed by introducing a new CRD without the prohibited fields.
> 
> This is just a remark and not a proposal in this story, right?

I'll create a new issue for implementing a new CRD

**Comment by filariow** [comment]
superseded by #296
