### ISSUE TITLE
Support acceptance tests on non-kind clusters

### ISSUE THREAD

**Issue by sadlerap** [primaza/primaza#65]
I'd like to be able to provide a cluster to run acceptance tests on.  This gives us a few benefits:
- We can pre-create testing clusters, so we don't have to wait forever for `kind` to spin up clusters during testing.  This should speed up test turnaround times.
- This will let us more accurately test user environments (for instance, testing directly on EKS).

**Comment by filariow** [comment]
@sadlerap can we close this issue as implemented #217
